services:
  - type: web
    name: processamento-imagens
    runtime: python
    buildCommand: pip install -r webapp/requirements.txt
    startCommand: cd webapp && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
